<?php

namespace SUH\GestionBundle\Entity;

/**
 * AdaptationDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdaptationDocumentsRepository extends \Doctrine\ORM\EntityRepository
{
}
