<?php

namespace SUH\GestionBundle\Entity;

/**
 * EtudiantEtudiantInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantEtudiantInformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
