<?php

namespace SUH\GestionBundle\Entity;

/**
 * EtudiantEtudiantHandicapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantEtudiantHandicapeRepository extends \Doctrine\ORM\EntityRepository
{
}
