<?php

namespace SUH\GestionBundle\Entity;

/**
 * EtudiantInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantInformationsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getStudentByStudentInformationsId($idInfos)
	{
		return $this->_em->createQueryBuilder()
				->select('e.id')
				->from('SUH\GestionBundle\Entity\EtudiantEtudiantInformations','ein')
				->where('ein.id = :id')
				->setParameter('id', $idInfos)
				->getOneOrNullResult();
	}
}

