<?php

namespace SUH\GestionBundle\Entity;

/**
 * NotificationSavsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSavsRepository extends \Doctrine\ORM\EntityRepository
{
}
