<?php

namespace SUH\GestionBundle\Entity;

/**
 * OrdinateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdinateurRepository extends \Doctrine\ORM\EntityRepository
{
}
