suh_connexion:
    resource: "@SUHConnexionBundle/Resources/config/routing.yml"
    prefix:   /

suh_gestion:
    resource: "@SUHGestionBundle/Resources/config/routing.yml"
    prefix:   /gestion

suh_contrat:
    resource: "@SUHContratBundle/Resources/config/routing.yml"
    prefix:   /contrat

#login
login:
    pattern: /login
    defaults: { _controller: SUHConnexionBundle:Connexion:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout



#accueil étudiant
suh_etudiant_homepageEtudiant:
    path:       /etudiant
    defaults: { _controller: SUHContratBundle:HeureEffectuee:addHeureEffectuee }

suh_etudiant_heuresEtudiant:
    path:    /etudiant/mesHeures
    defaults: { _controller: SUHContratBundle:Affichage:afficherHeureEspaceEtudiant}

suh_etudiant_heuresEtudiant_editer:
    path:    /etudiant/mesHeures/edit/{idHeure}
    defaults: { _controller: SUHContratBundle:HeureEffectuee:editHeureEffectuee}
    requirements:
        idHeure: "^[0-9]+$"

suh_etudiant_heuresEtudiant_delete:
    path:    /etudiant/mesHeures/delete/{idHeure}
    defaults: { _controller: SUHContratBundle:HeureEffectuee:deleteHeureEffectuee}
    requirements:
        idHeure: "^[0-9]+$"

