
#accueil
suh_contrat_homepage:
    path:     /
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilContrat }


#gestion ajout
suh_contrat_addEtudiantAidant:
    path: /add
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:addEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

