<?php

namespace SUH\ContratBundle\Entity;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{

public function getPage($page=1, $maxepage=4){


}

}
