<?php

namespace SUH\ContratBundle\Entity;

/**
 * EtudiantAidantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantAidantRepository extends \Doctrine\ORM\EntityRepository
{


}
