<?php

namespace SUH\ContratBundle\Entity;

/**
 * HeureEffectueeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureEffectueeRepository extends \Doctrine\ORM\EntityRepository
{
}
