<?php

namespace SUH\ContratBundle\Entity;

/**
 * HeureEffectueeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureEffectueeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getHeureEffectuee($contrat){
        $q = $this->createQueryBuilder('c')
            ->where('c.contrat = :contrat')
            ->setParameter('contrat', $contrat);



        return $q;
    }

    public function selectNbHeurePourUnEtudiantPourUnContrat($etudiant, $contrat){
        $query = $this->_em->createQuery('SELECT h
                                          FROM SUHContratBundle:HeureEffectuee h
                                          JOIN h.contrat c JOIN c.etudiantAidant e 
                                          WHERE e.id = :idEtudiant
                                          AND c.id = :idContrat');
        $query->setParameter('idEtudiant', $etudiant->getId());
        $query->setParameter('idContrat', $contrat->getId());

        $results = $query->getSingleResult();

        return $results;

    }

    public function selectNbHeurePourUnEtudiant($etudiant){
        $query = $this->_em->createQuery('SELECT SUM(h.nbHeure) 
                                          FROM SUHContratBundle:HeureEffectuee h
                                          JOIN h.contrat c JOIN c.etudiantAidant e 
                                          WHERE e.id = :id');
        $query->setParameter('id', $etudiant->getId());
        $results = $query->getSingleResult();

        return $results;

    }

    public function selectNbHeureValidePourUnEtudiant($etudiant){
    $query = $this->_em->createQuery('SELECT SUM(h.nbHeure)
                                          FROM SUHContratBundle:HeureEffectuee h
                                          JOIN h.contrat c JOIN c.etudiantAidant e 
                                          WHERE e.id = :id
                                          AND h.verification = 1
                                          GROUP BY MONTH(h.dateAndTime)');

    $query->setParameter('id', $etudiant->getId());
    $results = $query->getResult();

    return $results;

    }
    public function selectNbHeureNonValidePourUnEtudiant($etudiant){

        $query = $this->_em->createQuery('SELECT SUM(h.nbHeure)
                                          FROM SUHContratBundle:HeureEffectuee h
                                          JOIN h.contrat c JOIN c.etudiantAidant e 
                                          WHERE e.id = :id
                                          AND h.verification = 0');

        $query->setParameter('id', $etudiant->getId());
        $results = $query->getSingleResult();

        return $results;

    }
}
