<?php

namespace Proxies\__CG__\SUH\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etudiant extends \SUH\GestionBundle\Entity\Etudiant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'numeroEtudiant', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'dateNaissance', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'premiereInscription', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantInformations', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantFormation', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantHandicape'];
        }

        return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'numeroEtudiant', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'dateNaissance', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'premiereInscription', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantInformations', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantFormation', '' . "\0" . 'SUH\\GestionBundle\\Entity\\Etudiant' . "\0" . 'listEtudiantHandicape'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etudiant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEtudiant($numeroEtudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEtudiant', [$numeroEtudiant]);

        return parent::setNumeroEtudiant($numeroEtudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEtudiant', []);

        return parent::getNumeroEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremiereInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremiereInscription', []);

        return parent::getPremiereInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremiereInscription($premiereInscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremiereInscription', [$premiereInscription]);

        return parent::setPremiereInscription($premiereInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function addListEtudiantInformations($listEtudiantInformations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListEtudiantInformations', [$listEtudiantInformations]);

        return parent::addListEtudiantInformations($listEtudiantInformations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListEtudiantInformations($listEtudiantInformations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListEtudiantInformations', [$listEtudiantInformations]);

        return parent::removeListEtudiantInformations($listEtudiantInformations);
    }

    /**
     * {@inheritDoc}
     */
    public function getListEtudiantInformations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListEtudiantInformations', []);

        return parent::getListEtudiantInformations();
    }

    /**
     * {@inheritDoc}
     */
    public function addListEtudiantFormation($listEtudiantFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListEtudiantFormation', [$listEtudiantFormation]);

        return parent::addListEtudiantFormation($listEtudiantFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListEtudiantFormation($listEtudiantFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListEtudiantFormation', [$listEtudiantFormation]);

        return parent::removeListEtudiantFormation($listEtudiantFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getListEtudiantFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListEtudiantFormation', []);

        return parent::getListEtudiantFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function addListEtudiantHandicape($listEtudiantHandicape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListEtudiantHandicape', [$listEtudiantHandicape]);

        return parent::addListEtudiantHandicape($listEtudiantHandicape);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListEtudiantHandicape($listEtudiantHandicape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListEtudiantHandicape', [$listEtudiantHandicape]);

        return parent::removeListEtudiantHandicape($listEtudiantHandicape);
    }

    /**
     * {@inheritDoc}
     */
    public function getListEtudiantHandicape()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListEtudiantHandicape', []);

        return parent::getListEtudiantHandicape();
    }

    /**
     * {@inheritDoc}
     */
    public function addListEtudiantInformation(\SUH\GestionBundle\Entity\EtudiantEtudiantInformations $listEtudiantInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListEtudiantInformation', [$listEtudiantInformation]);

        return parent::addListEtudiantInformation($listEtudiantInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListEtudiantInformation(\SUH\GestionBundle\Entity\EtudiantEtudiantInformations $listEtudiantInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListEtudiantInformation', [$listEtudiantInformation]);

        return parent::removeListEtudiantInformation($listEtudiantInformation);
    }

}
