<?php

namespace Proxies\__CG__\SUH\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AideExamen extends \SUH\GestionBundle\Entity\AideExamen implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'amenagementExamens', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'avisMedical', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'tempsMajore', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'dateValidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'dureeAvisMedical', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'adaptationDocuments', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'materiel', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'ordinateur', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'secretaireExamen', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'delocalisationExamen'];
        }

        return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'amenagementExamens', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'avisMedical', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'tempsMajore', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'dateValidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'dureeAvisMedical', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'adaptationDocuments', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'materiel', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'ordinateur', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'secretaireExamen', '' . "\0" . 'SUH\\GestionBundle\\Entity\\AideExamen' . "\0" . 'delocalisationExamen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AideExamen $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAvisMedical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvisMedical', []);

        return parent::getAvisMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvisMedical($avisMedical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvisMedical', [$avisMedical]);

        return parent::setAvisMedical($avisMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriel', []);

        return parent::getMateriel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriel($materiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriel', [$materiel]);

        return parent::setMateriel($materiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdinateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdinateur', []);

        return parent::getOrdinateur();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdinateur($ordinateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdinateur', [$ordinateur]);

        return parent::addOrdinateur($ordinateur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdinateur($ordinateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdinateur', [$ordinateur]);

        return parent::removeOrdinateur($ordinateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdaptationDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdaptationDocuments', []);

        return parent::getAdaptationDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdaptationDocuments($adaptationDocuments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdaptationDocuments', [$adaptationDocuments]);

        return parent::addAdaptationDocuments($adaptationDocuments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdaptationDocuments($adaptationDocuments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdaptationDocuments', [$adaptationDocuments]);

        return parent::removeAdaptationDocuments($adaptationDocuments);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmenagementExamens($amenagementExamens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmenagementExamens', [$amenagementExamens]);

        return parent::setAmenagementExamens($amenagementExamens);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmenagementExamens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmenagementExamens', []);

        return parent::getAmenagementExamens();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempsMajore($tempsMajore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempsMajore', [$tempsMajore]);

        return parent::setTempsMajore($tempsMajore);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempsMajore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempsMajore', []);

        return parent::getTempsMajore();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecretaireExamen($secretaireExamen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecretaireExamen', [$secretaireExamen]);

        return parent::setSecretaireExamen($secretaireExamen);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecretaireExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecretaireExamen', []);

        return parent::getSecretaireExamen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelocalisationExamen($delocalisationExamen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelocalisationExamen', [$delocalisationExamen]);

        return parent::setDelocalisationExamen($delocalisationExamen);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelocalisationExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelocalisationExamen', []);

        return parent::getDelocalisationExamen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateValidite($dateValidite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateValidite', [$dateValidite]);

        return parent::setDateValidite($dateValidite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateValidite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateValidite', []);

        return parent::getDateValidite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeAvisMedical($dureeAvisMedical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeAvisMedical', [$dureeAvisMedical]);

        return parent::setDureeAvisMedical($dureeAvisMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeAvisMedical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeAvisMedical', []);

        return parent::getDureeAvisMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdaptationDocument(\SUH\GestionBundle\Entity\AdaptationDocuments $adaptationDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdaptationDocument', [$adaptationDocument]);

        return parent::addAdaptationDocument($adaptationDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdaptationDocument(\SUH\GestionBundle\Entity\AdaptationDocuments $adaptationDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdaptationDocument', [$adaptationDocument]);

        return parent::removeAdaptationDocument($adaptationDocument);
    }

}
