<?php

namespace Proxies\__CG__\SUH\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EtudiantHandicape extends \SUH\GestionBundle\Entity\EtudiantHandicape implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'qhandi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'rqth', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'notificationSavs', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'amenagementEtude', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'tauxInvalidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'suivi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'typeAllocations', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'descriptifComplementaire', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeMdphEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeRqthEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeNotificationSavsEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'mdph', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'handicap', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'aideExamen'];
        }

        return ['__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'qhandi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'rqth', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'notificationSavs', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'amenagementEtude', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'tauxInvalidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'suivi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'typeAllocations', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'descriptifComplementaire', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeMdphEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeRqthEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'demandeNotificationSavsEnCours', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'mdph', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'handicap', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'aideExamen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EtudiantHandicape $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAideExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAideExamen', []);

        return parent::getAideExamen();
    }

    /**
     * {@inheritDoc}
     */
    public function setAideExamen($aideExamen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAideExamen', [$aideExamen]);

        return parent::setAideExamen($aideExamen);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmenagementEtude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmenagementEtude', []);

        return parent::getAmenagementEtude();
    }

    /**
     * {@inheritDoc}
     */
    public function addAmenagementEtude($amenagementEtude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAmenagementEtude', [$amenagementEtude]);

        return parent::addAmenagementEtude($amenagementEtude);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAmenagementEtude($amenagementEtude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAmenagementEtude', [$amenagementEtude]);

        return parent::removeAmenagementEtude($amenagementEtude);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandicap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandicap', []);

        return parent::getHandicap();
    }

    /**
     * {@inheritDoc}
     */
    public function addHandicap($handicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHandicap', [$handicap]);

        return parent::addHandicap($handicap);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHandicap($handicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHandicap', [$handicap]);

        return parent::removeHandicap($handicap);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdph', []);

        return parent::getMdph();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdph($mdph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdph', [$mdph]);

        return parent::setMdph($mdph);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setQhandi($qhandi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQhandi', [$qhandi]);

        return parent::setQhandi($qhandi);
    }

    /**
     * {@inheritDoc}
     */
    public function getQhandi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQhandi', []);

        return parent::getQhandi();
    }

    /**
     * {@inheritDoc}
     */
    public function setRqth($rqth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRqth', [$rqth]);

        return parent::setRqth($rqth);
    }

    /**
     * {@inheritDoc}
     */
    public function getRqth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRqth', []);

        return parent::getRqth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeMdphEnCours($demandeMdphEnCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeMdphEnCours', [$demandeMdphEnCours]);

        return parent::setDemandeMdphEnCours($demandeMdphEnCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeMdphEnCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeMdphEnCours', []);

        return parent::getDemandeMdphEnCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeRqthEnCours($demandeRqthEnCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeRqthEnCours', [$demandeRqthEnCours]);

        return parent::setDemandeRqthEnCours($demandeRqthEnCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeRqthEnCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeRqthEnCours', []);

        return parent::getDemandeRqthEnCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeNotificationSavsEnCours($demandeNotificationSavsEnCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeNotificationSavsEnCours', [$demandeNotificationSavsEnCours]);

        return parent::setDemandeNotificationSavsEnCours($demandeNotificationSavsEnCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeNotificationSavsEnCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeNotificationSavsEnCours', []);

        return parent::getDemandeNotificationSavsEnCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationSavs($notificationSavs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationSavs', [$notificationSavs]);

        return parent::setNotificationSavs($notificationSavs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationSavs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationSavs', []);

        return parent::getNotificationSavs();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmenagementEtude($amenagementEtude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmenagementEtude', [$amenagementEtude]);

        return parent::setAmenagementEtude($amenagementEtude);
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxInvalidite($tauxInvalidite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxInvalidite', [$tauxInvalidite]);

        return parent::setTauxInvalidite($tauxInvalidite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxInvalidite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxInvalidite', []);

        return parent::getTauxInvalidite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuivi($suivi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuivi', [$suivi]);

        return parent::setSuivi($suivi);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuivi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuivi', []);

        return parent::getSuivi();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptifComplementaire($descriptifComplementaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptifComplementaire', [$descriptifComplementaire]);

        return parent::setDescriptifComplementaire($descriptifComplementaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptifComplementaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptifComplementaire', []);

        return parent::getDescriptifComplementaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAllocations($typeAllocations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAllocations', [$typeAllocations]);

        return parent::setTypeAllocations($typeAllocations);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAllocations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAllocations', []);

        return parent::getTypeAllocations();
    }

}
