
#accueil
suh_contrat_homepage:
    path:     /
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilContrat }


#=========================================
#============Gestion Contrats=============
#=========================================

#Afficher les contrats pour un étudiant
suh_contrat_afficherContrat:
    path: /{idEtudiant}/contrats/{page}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherContratsPourUnEtudiant, page:1}
    requirements:
           idEtudiant: "^[0-9]+$"

#ajouter un contrat étudiant
suh_contrat_addContrat:
    path: /{idEtudiant}/addContrat
    defaults: {_controller: SUHContratBundle:Contrat:addContrat}
    requirements:
       idEtudiant: "^[0-9]+$"

suh_contrat_archiverContrat:
    path: /archiver/{idContrat}
    defaults: {_controller: SUHContratBundle:Contrat:archiverContrat}
    requirements:
        idContrat: "^[0-9]+$"

#edit un contrat étudiant
suh_contrat_editerContrat:
    path: /editContrat/{idContrat}
    defaults: {_controller: SUHContratBundle:Contrat:editContrat }
    requirements:
           idContrat: "^[0-9]+$"

#supprimer un contrat étudiant
suh_contrat_deleteContrat:
    path: /deleteContrat/{idContrat}
    defaults: {_controller: SUHContratBundle:Contrat:deleteContrat}
    requirements:
       idContrat: "^[0-9]+$"

#add date envoi contrat étudiant
suh_contrat_addDateContrat:
    path: /addDateContrat/{idContrat}
    defaults: {_controller: SUHContratBundle:Contrat:addDateContrat}
    requirements:
       idContrat: "^[0-9]+$"
       
#affichage archives
suh_contrat_showArchive:
    path: /{idEtudiant}/contrats/archives/{page}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherArchiveContratAction, page:1}
    requirements:
           idEtudiant: "^[0-9]+$"


#=========================================
#============Gestion Etudiants============
#=========================================
#gestion ajout
suh_contrat_addEtudiantAidant:
    path: /addEtudiant
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:addEtudiantAidant }


#gestion get
suh_contrat_getEtudiantAidant:
    path: /getEtudiant/{id}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherGetEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#gestion show
suh_contrat_showEtudiantAidant:
    path: /showEtudiant/{id}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherShowEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#gestion edit
suh_contrat_editEtudiantAidant:
    path: /editEtudiant/{id}
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:editEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#gestion suppr
suh_contrat_delEtudiantAidant:
    path: /supprimer/{id}
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:delEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#=========================================
#=========Exportation Importation=========
#=========================================

suh_contrat_exportationContrat:
    path: /exporterContratPDF/{idContrat}
    defaults: { _controller: SUHContratBundle:ImportExport:exportContratPDF }
    requirements:
        idContrat:   "^[0-9]+$"