
#accueil
suh_contrat_homepage:
    path:     /
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilContrat }

#accueil étudiant
suh_contrat_homepageEtudiant:
    path:       /etudiant
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilEtudiant }

#Afficher les contrats pour un étudiant
suh_contrat_afficherContrat:
    path:    /contrats/{idEtudiant}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherContratsPourUnEtudiant}
    requirements:
           idEtudiant: "^[0-9]+$"

#ajouter un contrat étudiant
suh_contrat_addContrat:
    path: /addContrat/{idEtudiant}
    defaults: {_controller: SUHContratBundle:Contrat:addContrat}
    requirements:
       idEtudiant: "^[0-9]+$"

#supprimer un contrat étudiant
suh_contrat_deleteContrat:
    path: /deleteContrat/{idContrat}
    defaults: {_controller: SUHContratBundle:Contrat:deleteContrat}
    requirements:
       idContrat: "^[0-9]+$"



#gestion ajout
suh_contrat_addEtudiantAidant:
    path: /add
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:addEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

