
#accueil
suh_contrat_homepage:
    path:     /
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilContrat }

#accueil étudiant
suh_contrat_homepageEtudiant:
    path:       /etudiant
    defaults: { _controller: SUHContratBundle:Affichage:AfficherAccueilEtudiant }

#Afficher les contrats pour un étudiant
suh_contrat_afficherContrat:
    path:    /contrats/{idEtudiant}
    defaults: { _controller: SUHContratBundle:Affichage:AfficherContratsPourUnEtudiant}
    requirements:
           idEtudiant: "^[0-9]+$"

#ajouter un contrat étudiant
suh_contrat_addContrat:
    path: /addContrat/{idEtudiant}
    defaults: {_controller: SUHContratBundle:Contrat:addContrat}
    requirements:
       idEtudiant: "^[0-9]+$"



#gestion ajout
suh_contrat_addEtudiantAidant:
    path: /addEtudiant
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:addEtudiantAidant }


#gestion get
suh_contrat_getEtudiantAidant:
    path: /getEtudiant/{id}
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:getEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#gestion edit
suh_contrat_editEtudiantAidant:
    path: /modifier/{id}
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:editEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"

#gestion suppr
suh_contrat_editEtudiantAidant:
    path: /delEtudiant/{id}
    defaults: { _controller: SUHContratBundle:GestionEtudiantAidant:delEtudiantAidant }
    requirements:
        id:   "^[0-9]+$"