<?php

namespace SUH\ConnexionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getNbUser()
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('count(user.id)')
                ->from('SUHConnexionBundle:User','user');
        
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findByRole($role) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' . $role . '"%');
        return $qb->getQuery()->getResult();
    }
}
